"use client";

import { acceptAupAction } from "@/app/(chat)/aup/actions";
import { ShieldCheck } from "lucide-react";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Button } from "ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "ui/card";
import { ScrollArea } from "ui/scroll-area";

interface AupClientProps {
  version: string;
}

export function AupClient({ version }: AupClientProps) {
  const [agreed, setAgreed] = useState(false);
  const [pending, startTransition] = useTransition();

  const handleAccept = () => {
    startTransition(async () => {
      try {
        await acceptAupAction();
      } catch (err) {
        // acceptAupAction ends in redirect(), which throws a NEXT_REDIRECT
        // control-flow error — let that propagate so navigation still happens.
        const digest =
          err && typeof err === "object" && "digest" in err
            ? String((err as { digest?: unknown }).digest)
            : "";
        if (digest.startsWith("NEXT_REDIRECT")) throw err;
        // A genuine failure: re-enable the button and tell the user.
        toast.error(
          "Could not record your acceptance. Please try again or contact your administrator.",
        );
      }
    });
  };

  return (
    <Card className="w-full max-w-sm sm:max-w-2xl shadow-sm animate-in fade-in slide-in-from-bottom-2 duration-500">
      <CardHeader className="space-y-2">
        <div className="flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-primary" />
          <CardTitle className="font-display tracking-tight">
            Acceptable Use Policy
          </CardTitle>
        </div>
        <p className="text-sm text-muted-foreground">
          Version {version} — Please read and accept before using Conek AI.
        </p>
      </CardHeader>

      <CardContent>
        <ScrollArea className="h-80 rounded-xl border p-4 text-sm leading-relaxed space-y-4">
          <h2 className="font-semibold">
            1. AI Transparency (EU AI Act, Article 50)
          </h2>
          <p>
            You are interacting with an AI system powered by large language
            models. Responses are generated by AI and may be inaccurate,
            incomplete, or outdated. Always verify important information from
            authoritative sources before acting on it.
          </p>

          <h2 className="font-semibold mt-4">2. Authorised Use</h2>
          <p>
            Conek AI is for professional use by A Safe Digital employees. Use it
            to assist with legitimate work tasks. Do not use it for personal,
            commercial, or unlawful purposes.
          </p>

          <h2 className="font-semibold mt-4">3. Data Protection (GDPR)</h2>
          <p>
            Your prompts and usage data are processed under A Safe Digital's
            data protection policy. Do not enter client personal data, sensitive
            health data, or any data you are not authorised to process in this
            system. You can request a copy or erasure of your data by contacting
            your administrator.
          </p>

          <h2 className="font-semibold mt-4">
            4. Prohibited Use — Employment Decisions (EU AI Act, Art. 26)
          </h2>
          <p>
            This tool must <strong>not</strong> be used to make or support
            automated decisions about hiring, firing, performance grading, or
            disciplinary action. Such use is technically blocked and is
            explicitly prohibited. Violations must be reported.
          </p>

          <h2 className="font-semibold mt-4">5. Confidentiality</h2>
          <p>
            Do not enter A Safe Digital's trade secrets, client confidential
            information, or third-party proprietary material. All input is
            subject to processing by the AI provider via OpenRouter under
            data-processing agreements.
          </p>

          <h2 className="font-semibold mt-4">6. Credentials & Secrets</h2>
          <p>
            Never paste API keys, passwords, private keys, or access tokens. The
            system includes automatic detection, but you remain responsible for
            what you submit.
          </p>

          <h2 className="font-semibold mt-4">7. Monitoring</h2>
          <p>
            Usage is logged for security, compliance, and cost attribution
            purposes. Logs are accessible to authorised administrators and
            retained for a minimum of 6 months per EU AI Act requirements.
          </p>

          <h2 className="font-semibold mt-4">8. Liability</h2>
          <p>
            A Safe Digital accepts no liability for decisions made on the basis
            of AI output. You are responsible for verifying the accuracy and
            legality of any AI-assisted work before it reaches clients or
            affects others.
          </p>
        </ScrollArea>
      </CardContent>

      <CardFooter className="flex flex-col gap-3">
        <label className="flex items-start gap-2 text-sm cursor-pointer">
          <input
            type="checkbox"
            className="mt-0.5 h-4 w-4 accent-primary"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
            data-testid="aup-agree-checkbox"
          />
          <span>
            I have read and agree to the Acceptable Use Policy. I understand
            that my use of Conek AI is logged and subject to these terms.
          </span>
        </label>

        <Button
          className="w-full"
          disabled={!agreed || pending}
          onClick={handleAccept}
          data-testid="aup-accept-btn"
        >
          {pending ? "Saving…" : "Accept and Continue"}
        </Button>
      </CardFooter>
    </Card>
  );
}
